### ISSUE TITLE
Reason to not support armv7l

### ISSUE THREAD

**Issue by tcassaert** [voxpupuli/puppet-nomad#17]
Is there a specific reason why armv7l is not supported by this module?

**Comment by attachmentgenie** [comment]
@tcassaert according to https://github.com/voxpupuli/puppet-nomad/blame/master/manifests/params.pp#L19 it should be supported is there another place in the code that prevents this module from supporting it?

**Comment by tcassaert** [comment]
My mirror of this module dated from commit c6b88a0489c70e19e64b5a92734b4ea49847bd6a, where this ARM support was not yet available. So this issue is outdated. Thanks for checking!
