### ISSUE TITLE
Push puppet module 0.0.4 to forge

### ISSUE THREAD

**Issue by spuder** [voxpupuli/puppet-nomad#20]
This commit does not appear to be present in the 0.0.3 module distributed to the puppet-forge

https://github.com/dudemcbacon/puppet-nomad/commit/2f35204d28083deaee5fdd0d70ff8c6cbf91c70f

As a result config.pp contains this incorrect config
```
      'systemd' : {
        file { '/etc/sysconfig/nomad':
          ensure => directory,
          mode   => '0644',
          owner  => 'root',
          group  => 'root',
        }->
```

When it should be

```
      'systemd' : {
        file { '/etc/sysconfig':
          ensure => directory,
          mode   => '0644',
          owner  => 'root',
          group  => 'root',
        }->
```

Puppet module 0.0.3 was pushed April 15, 2016 to the forge which means it was most likely running this commit 

https://github.com/dudemcbacon/puppet-nomad/commit/f9a30ea207abd95660766b9f860ef4df7c247147

## workaround

Add the following to your environment Puppetfile, then run `r10k puppetfile install`
```
mod 'nomad', :git => 'https://github.com/dudemcbacon/puppet-nomad', :commit => 'a6587bca54dc3513d904b819a93f7085f3778491'
```

**Comment by spuder** [comment]
I would really like to see the new version pushed to the puppet forge since the last release was July 2019 and there have been several fixes since then. Humbly asking that this get pushed soon. 

![Screen Shot 2020-11-09 at 4 36 04 PM](https://user-images.githubusercontent.com/242382/98609101-d39c8600-22a9-11eb-9f0d-08790ec019a0.png)

**Comment by attachmentgenie** [comment]
0.0.4 has been pushed to the forge => https://forge.puppet.com/modules/puppet/nomad
