### ISSUE TITLE
donate this module to voxpupuli

### ISSUE THREAD

**Issue by attachmentgenie** [voxpupuli/puppet-nomad#21]
since you seem to not maintain this module would you be willing to move this repo to https://github.com/voxpupuli where we could look after this module?

- [x] Ask one of the Administrators to add you to the incoming-migrations team.
- [x] At that point you can transfer your own repository.
- [x] If migrating a module from puppetlabs, re-enable github issues.
- [x] Verify that all webhooks are disabled.
- [x] Update the README.md with a description of the deprecation and a link to the new module location.
- [x] Release a copy of your module to the ‘puppet’ forge account.
- [x] Add the module to our modulesync setup.
~~- [x ] Add the module to our plumbing repository(plumbing).~~
- [x] Ask an admin to add the collaborators team to the module’s Collaborators & Teams ‘Teams’ list with Write permissions (e.g. https://github.com/voxpupuli/puppet-gitlab/settings/collaboration)).
- [x] Execute modulesync for this module.
- [x] Create a Jira issue at https://tickets.puppetlabs.com and ask to deprecate the old module (and approve the new one if the old one was approved as well).
- [x] Ensure that there isn’t a CONTRIBUTING.md file in the docroot. Our modulesync will place one at .github/CONTRIBUTING.md. Please enhance our existing template if the version in the docroot contains useful parts.
- [x] Ensure that the module has a correct LICENSE file in the docroot that matches the mentioned license in the metadata.json.

**Comment by traylenator** [comment]
@dudemcbacon this would be great ?

**Comment by dudemcbacon** [comment]
@attachmentgenie How do I donate the module?

**Comment by attachmentgenie** [comment]
@dudemcbacon => https://voxpupuli.org/docs/migrate_module/

If you are interested in helping maintaining the module in vox pupuli i can ping the right person to get you access. If not i am already a member of the incoming-migrations teams and would be able to take it from there

**Comment by dudemcbacon** [comment]
If you give me the appropriate permissions, I will transfer it. I no longer have the time to maintain it.

**Comment by traylenator** [comment]
@dudemcbacon happy to help out once transferred.

**Comment by traylenator** [comment]
@dudemcbacon you should have an invite to get permissions now.

**Comment by attachmentgenie** [comment]
@dudemcbacon can i help with anything to get the migration going?

**Comment by dudemcbacon** [comment]
@attachmentgenie I have transfered this repo. Apologies it took so long, I had mistakenly transfered it to 'voxpopuli' and didn't realize until a few days ago.

**Comment by attachmentgenie** [comment]
Thanks!

**Comment by bastelfreak** [comment]
@attachmentgenie will you continue the migration process ( 
 https://voxpupuli.org/docs/migrate_module/ https://github.com/voxpupuli/voxpupuli.github.io/pull/231/files )?

**Comment by attachmentgenie** [comment]
@bastelfreak yes I will!

**Comment by attachmentgenie** [comment]
@bastelfreak can you add the collaborators team to this repo please?

**Comment by bastelfreak** [comment]
@attachmentgenie done, permissions should be fine now.

**Comment by attachmentgenie** [comment]
@bastelfreak if you could check the webhooks than i think i got through all of them. just need to get github actions to pass.
