### ISSUE TITLE
Do not monkey patch JSON function

### ISSUE THREAD

**Issue by traylenator** [voxpupuli/puppet-nomad#23]
Note this applies to the current function and the function using the autoconverted to APIv4 patches.

The monkey patch of JSON breaks all of puppet as per.

https://github.com/solarkennedy/puppet-consul/pull/456

example fix.

**Comment by attachmentgenie** [comment]
lets see if we can make this a more general solution => puppet-extlib/issues/174

**Comment by ekohl** [comment]
I do wonder why the regular `.to_json` is insufficient. Is the output unstable that it needs to be sorted?

**Comment by attachmentgenie** [comment]
extlib wasnt the right place i opened => https://tickets.puppetlabs.com/browse/MODULES-10904 lets see how that progresses.

@ekohl will have to do some experiments to see how `.to_json`  behaves.

In the mean time i am debating whether or not to move this function in the the newly create puppet-hashi_stack module in the mean time if `.to_json` doesnt give the results we are after

**Comment by ekohl** [comment]
Sounds like a good plan.

**Comment by attachmentgenie** [comment]
my initial tests make me think that switching to `.to_json` should be sufficient as the output is stable in 10 consecutive runs
