### ISSUE TITLE
get systemd file in sync with upstream version

### ISSUE THREAD

**Issue by attachmentgenie** [voxpupuli/puppet-nomad#33]
should be in sync with https://github.com/hashicorp/nomad/blob/master/dist/systemd/nomad.service

**Comment by star3am** [comment]
@attachmentgenie Hallo there, I just submitted this PR https://github.com/voxpupuli/puppet-nomad/pull/38 is there anything else you'd like me to add? 

Thanks for opening the issue! Have a nice day
