### ISSUE TITLE
add option to manage the upstream repo

### ISSUE THREAD

**Issue by attachmentgenie** [voxpupuli/puppet-nomad#35]
see [1] for the announcements and instructions

[1]https://www.hashicorp.com/blog/announcing-the-hashicorp-linux-repository

**Comment by ekohl** [comment]
I wonder if you still want to support the archive versions after this or make it package-only.

**Comment by attachmentgenie** [comment]
thats an interesting thought, my brain didnt even go there yet. not sure the repos support all the architecture yet though

**Comment by attachmentgenie** [comment]
current support seems to be x64 only

**Comment by ekohl** [comment]
Do you think it makes sense to reach out to upstream about other architectures? If they build archives for it, it makes sense that they want to support other architectures too.

**Comment by attachmentgenie** [comment]
We can tdy but i am not holding my breath. It took them years of community requests to start packaging in the first place
