### ISSUE TITLE
Remove the environmentFile from service file

### ISSUE THREAD

**Issue by attachmentgenie** [voxpupuli/puppet-nomad#39]
## How to reproduce (e.g Puppet code you use)

run on debian family

## What are you seeing

EnvironmentFile is configured from RedHat family only (/etc/sysconfig/nomad)

## What behaviour did you expect instead

paraterized based on family

**Comment by ekohl** [comment]
For what it's worth, I generally avoid `/etc/sysconfig` nowadays and use systemd drop-ins to set environment variables. The benefit is that it's unified for all distros while `/etc/sysconfig` is different from `/etc/default` on Debian. You can also see the exact config using `systemctl cat nomad` when using drop-ins.

**Comment by attachmentgenie** [comment]
@ekohl another good point, i believe thats a better way forward and that line isnt in the upstream service file either.
