### ISSUE TITLE
add support for Ubuntu22.04

### ISSUE THREAD

**Issue by maxadamo** [voxpupuli/puppet-nomad#86]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.x / 7.x/ 
- Ruby:  2.5 / 2.7
- Distribution: Ubuntu 22.04
- Module version: 2.2.0

## How to reproduce (e.g Puppet code you use)

n/a

## What are you seeing

Ubuntu 22.04 is missing from the support matrix

## What behaviour did you expect instead

Having Ubuntu 22.04

## Output log

n/a

## Any additional information you'd like to impart

It's not much different from Ubuntu 20.04. We need to add to the list of supported OS and run the additional tests

**Comment by zilchms** [comment]
completed in #96
